test3_A test3_B test3_C test3_D test3_E : test3_A.cpp test3_B.cpp test3_C.cpp test3_D.cpp test3_E.cpp
	g++ test3_A.cpp -o test3_A
	g++ test3_B.cpp -o test3_B
	g++ test3_C.cpp -o test3_C
	g++ test3_D.cpp -o test3_D
	g++ test3_E.cpp -o test3_E

.PHONY : clean

clean :
	rm test3_A test3_B test3_C test3_D test3_E
